<a href="https://colab.research.google.com/github/kim1minjii/pythondemo/blob/master/python_12_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###3차원 이상에서 차원 구분법

In [ ]:
import numpy as np

In [ ]:
#0부터 24미만까지 생성
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
#print하면 array라는 글자는 안보인다.
#공백은 그대로 보인다. -> 지원 구분 가능
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0, 1]

array([4, 5, 6, 7])

In [ ]:
b[1, 1]

array([16, 17, 18, 19])

In [ ]:
b[0, 1, 3]

7

###fancy indexing과 indexing 차이
- indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [ ]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원 -> 2차원)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#fancy indexing은 원래 3차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
#b[0]은 b[0, :, :]의 단축 표현이다.
b[[0], :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
#b의 0번째 공간, 1번째 행 미만, 열전체
b[0, :1, :]

array([[0, 1, 2, 3]])

###Ellipsis
...(Ellipsis)는 이후로 모든 것을 의미한다.

In [ ]:
b[0, :, :]

NameError: ignored

In [ ]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
type(...)

ellipsis

In [ ]:
b[0] #생략기법
b[0,:,:] #slicing기법
b[0,...] #Ellipsis기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#숫자 1, 5, 9만 가져온다.
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0, :, 1]

array([1, 5, 9])

In [ ]:
b[0,[0, 1, 2], :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#숫자 1, 5, 9, 3, 7, 11가져오기


In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0,:, [1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [ ]:
#숫자 4, 5, 6,7, 16, 17, 18, 19 가져오기
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[:,1,:] #[모든열,1,모든행]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
b[:, 1:2, :] #[모든열?공간?, 1에서 2미만, 모든행]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [ ]:
#3, 7, 11, 15, 19, 23 가져오기
#= 모든 행에 있는 마지막 열
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[:, 1:2,:] #모든공간, 1:2, 모든행

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [ ]:
b[:, :, 3:4] #모든공간,

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [ ]:
b[:, :, -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [ ]:
b[:, :, [3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [ ]:
c = b[:, :, 3] #2행 3열
c.shape

(2, 3)

In [ ]:
b[..., 3] #... = 전체
#결과(out)에 ...은 줄임표현

array([[ 3,  7, 11],
       [15, 19, 23]])

In [ ]:
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

####줄임표현(...)
출력해야 할 데이터 수가 엄청 클 때 보이는 ...은 Ellipsis와 다르다.

In [ ]:
np.set_printoptions(edgeitems=6) #out창에 앞뒤로 6개씩 나오게 하는 것

In [ ]:
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

###연산
numpy연산의 기본은 두 개의 shape이 같아야 한다.

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b = np.arange(1, 13).reshape(3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b.shape

(3, 4)

In [ ]:
#같은 위치의 원소끼리 더해 준다.(elementwise)
a + b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

numpy는 elementwise로 vectorize연산을 한다.  
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.

In [ ]:
#python의 list에서 + 연산자는 elementwise가 아니라 list를 확장시킨다.(연결)
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [ ]:
@np.vectorize #리스트인데 연산이 됨
def plus(a, b):
  return a+b

plus([1,2,3], [4,5,6]) #짝이 맞는 요소들끼리 계산(elementwise, vectorize)

array([5, 7, 9])

numpy는 python함수는 vectorize시키는 기능을 지원한다.


In [ ]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(6, 12).reshape(2, 3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a * b #elementwise

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
#python의 리스트끼리는 곱하기가 안된다.
[1, 2, 3] * [4, 5, 6]

TypeError: ignored

In [ ]:
type(np.array(3))

numpy.ndarray

In [ ]:
c = np.matrix([[1,2], [3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [ ]:
type(c)

numpy.matrix

numpy에서는 ndarry이외에 matrx라는 자료형도 존재한다.  
matrix에서는 *연산자는 행렬곱을 의미한다.

In [ ]:
#matrix * matrix = 행렬곱
# 1*1+2*3    1*2+2*4
# 3*1+4*3    3*2+4*4
c * c

matrix([[ 7, 10],
        [15, 22]])

ndarry에서 행렬곱 연산자 @이다.  
python재단에서 numpy를 위해 만들어준 연산자이다.  

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(2, 3)

In [ ]:
a @ b

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다.  
T는 transpose(전치)의 약자이다.

####전치행렬

In [ ]:
#전치행렬 : 행과 열을 바꾼다.
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

matrix는 @와 * 모두가 가능하다.

In [ ]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

In [ ]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

함수방법으로 np.dot()을 사용할 수 있다.

In [ ]:
np.dot(a, a.T) #ndarray

array([[ 5, 14],
       [14, 50]])

In [ ]:
np.dot(c, c.T) #matrix

matrix([[ 5, 11],
        [11, 25]])

method방법으로도 행렬곱 할 수 있다.
function방법과 사용하는 방법이 다르므로 주의한다.

In [ ]:
np.dot(a, a.T) #function 방식

array([[ 5, 14],
       [14, 50]])

In [ ]:
a.dot(a.T) #method방식

array([[ 5, 14],
       [14, 50]])

###broadcasting
python은 배열과 숫자 간에 연산을 할 수 있다.


In [ ]:
[1, 2, 3] + 1 #리스트 간 더하기가 안된다.

TypeError: ignored

같은 리스트일 때  
곱하기는 안되는데 더하기는 안됨    
리스트와 scalar일 때는  
더하기는 안되는데 곱하기는 됨

[1, 2, 3] + 1 (x)  
[1, 2, 3] + [1, 2, 3] (o) => 연결  
[1, 2, 3] * 1 (o) => 반복  
[1, 2, 3] * [1, 2, 3] (x)

In [ ]:
a = np.arange(6).reshape(2, 3) #리스트 아니고 배열 (ndarry)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

broadcasting이란 모양(shape)가 안맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.  
위 연산에서 1을 a와 같은 모양으로 만들어 준다.  
[[1, 1, 1],  
 [1, 1, 1]]

(1) broadcasting이 안되는 경우와 가능한 경우

In [ ]:
a #2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a + np.array([3, 4])

ValueError: ignored

In [ ]:
a + np.array([3, 4, 5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
a + np.array([[1], [2]]) #열1, 행2

array([[1, 2, 3],
       [5, 6, 7]])

### strides
strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다.  
c의 포인터 개념을 알고 있으면 이해하기가 쉽다.

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#행의 메모리 간격은 32bytes
#열의 메모리 간격은 4bytes
a.strides

(32, 8)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
#열의 원소개수 * itemsize = 행의 메모리 간격
#itemsize = 열의 메모리 간격
a.shape

(3, 4)

### axis
axis는 다차원 배열을 연산할 때 기준이 되는 축이다.

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

(0,0), (0,1), (0,2), (0,3)  
(1,0), (1,1), (1,2), (1,3)  
(2,0), (2,1), (2,2), (2,3)

In [ ]:
#a배열은 2차원이므로 axis=0은 행기준(행마다)
np.sum(a, axis=0) #axis=0(행)

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis=1) #a배열은 2차원이므로 axis=1은 열기준(열마다)

array([ 6, 22, 38])

axis는 3차원 이상에서도 사용할 수 있다.

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(0,0,1)(0,0,1)(0,0,2)(0,0,3)  
(0,1,1)(0,1,1)(0,1,2)(0,1,3)  
(0,2,1)(0,2,1)(0,2,2)(0,2,3)   
    
(1,0,1)(1,0,1)(1,0,2)(1,0,3)  
(1,1,1)(1,1,1)(1,1,2)(1,1,3)   
(1,2,1)(1,2,1)(1,2,2)(1,2,3)

In [ ]:
#a.sum(axix=0)
np.sum(a,axis=0) #공간기준(공간마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
#a.sum(axis=1)
np.sum(a, axis=1) #행기준(행마다)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [ ]:
#a.sum(axis=2)
np.sum(a, axis=2) #열기준(열마다)

array([[ 6, 22, 38],
       [54, 70, 86]])

3차원은 행렬에 공간(깊이)개념이 추가되었다고 할 수 있다.  
2차원(axis=0, axis=1)(행,열)  
3차원(axis=0, axis=1, axis=2)(공간, 행, 열)

###array모양 바꾸기

####(1)reshape
reshape는 차원을 바꿔주는 기능을 한다. 

In [ ]:
#signature대로 하면 a.reshape((3, 8))해야한다.
#하지만 reshape(3, 8)해도 내부적으로 이상없이 처리한다.
#reshape 수행 후의 값은 그대로 있다.
a = np.arange(24).reshape(3, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a = np.arange(24)
b = a.reshape(3, 8)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
#ValueError => 크기가 맞지 않음
a.reshape(2, 3, 5)

ValueError: ignored

In [ ]:
a.reshape(2, 3, -1) #마지막 값을 음수로 주면 알아서 맞춘다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#음수이기만 하면 -100도 상관없다.
a.reshape(2, 3, -100)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#음수를 2개 사용할 수는 없다.
#음수는 다른 차원들이 정해준 상황에서 남은 하나의 차원만 알아서 맞춰준다.
a.reshape(3, -1, -1)

ValueError: ignored

In [ ]:
a.reshape(3, -1, 2) #음수 값은 어느 위치든 상관 없음. 하나이면 된다.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

####(2) reshape으로 차원 늘리기

In [ ]:
#2차원
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#3차원
a = np.arange(6).reshape(2, 3, 1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

###resize
size는 원수 개수를 알려준다.

In [ ]:
a = np.arange(24)
print(a.size)
print(len(a))

24
24


In [ ]:
#a.resize(2, 3, 1)
np.resize(a, (2, 3, 1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
np.resize(a, (3, 2, 8)) # 3 * 2 * 8

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]])

In [ ]:
# 빈 공간은 0으로 채워줌
#mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape와 차이점1
#원래의 원소 개수와 변경하는 원소 개수가 안맞아도 된다.(0으로 채워준다) -> reshape와 차이점2
b = np.arange(24)
b.resize((2, 3, 8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

###array쪼개기

####split

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#a는 바뀌지 않으므로 재할당을 한다.
a = np.split(a, 2, axis=0)
a

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
a.shape

AttributeError: ignored

In [ ]:
print(type(a))
print(type(a[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
b = np.arange(24)
b = np.split(b, 2)
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
print(type(b))
print(type(b[1]))
print(b[1])
print(b[1][2]) #list
#print(b[1,2]) #TypeError => array

c = np.array(b)
print(c)
print(type(c))
print(c[1, 2])

<class 'list'>
<class 'numpy.ndarray'>
[12 13 14 15 16 17 18 19 20 21 22 23]
14
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>
14


####hsplit & vsplit

split은 axis파라미터가 있다. default: axis=0

In [ ]:
a = np.arange(24)
b = a.reshape(4, 6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
np.split(b, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
np.split(b, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [ ]:
#horizental(수평)
np.hsplit(a, 2) #a에 있는 값을 2개로 나눠

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
#vsplit은 1차원일 때 ValueError가 발생한다.
np.vsplit(b, 2) #2차원일 때 : Vertical(수직)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
np.hsplit(b, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

####indices_or_sections
split 시리즈 함수들의 두번째 파라미터 이름이 indices_or_sections이다.  
숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
np.split(a, 2)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [ ]:
#section
#처음부터 ~ 2미만 : [0, 1]
#2 ~ 3미만 : [2]
#3 ~ 끝까지 : [3, 4, 5...]
np.hsplit(a, (2, 3))

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

In [ ]:
#section
#처음부터 ~ 2미만 : [0, 1]
#2 ~ 3미만 : [2]
#3 ~ 8미만 : [3, 4, 5, 6, 7]
#8 ~ 끝까지 : [8, 9, 10...]
np.hsplit(a, (2, 3, 8))

[array([0, 1]),
 array([2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

### array합치기

In [ ]:
a = np.arange(24)
x, y, z = np.split(a, 3)

In [ ]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


#### hstack & vstack

In [ ]:
#hstack은 horizental(가로)로 합쳐준다.
np.hstack((x, y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# vstack은 vertical(세로)로 합쳐준다.
np.vstack((x, y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

#### dstack
dstack은 합쳐서 3차원으로 만들어 준다.  
합칠 array들이 1차원, 2차원일 경우는 차원을 늘린 후 합친다.
합쳐지는 차원은 axis = 2이다.


In [ ]:
print(x)
print(y)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [ ]:
#x는 shape 1차원 이므로 (1, m, 1)인 3차원으로 변환한다.
#y는 shape 1차원 이므로 (1, n, 1)인 3차원으로 변환한다.
#합쳐지는 차원은 axis=2이다.
c = np.dstack((x, y)) #(1, 8, 2)
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [ ]:
#x.shape
c.shape

(1, 8, 2)

#### concatenate
concatenate는 axis방향에 그대로 합쳐준다.
stack는 axis방향에 새로운 차원을 만들어 합쳐준다.

In [ ]:
a = np.arange(12).reshape(3, 4)
x, y = np.split(a, 2, axis = 1)

In [ ]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
# 원래 shape크기 그대로 유지를 한다.
np.concatenate((x, y)) #axis=0

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
#shape크기를 1개 증가해서 합친다.
np.stack((x, y))

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

###차원 확장

numpy는 차원을 확장하는 여러가지 방법이 있다.

####reshape

In [ ]:
#np.arange(12) : 1차원
#np.arnage(3, 4) : 2차원
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

####stack

In [ ]:
#3차원으로 확장
#tuple에 원소가 1개 있으면 차원만 확장 시켜준다.
np.stack((a, ))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

####nuwaxis
- 인덱싱할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a.shape #2차원

(3, 4)

In [ ]:
a[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
#a[np.newaxis]
a[np.newaxis, :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a[:, np.newaxis, :]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
a[:, np.newaxis, :].shape

(3, 1, 4)

In [ ]:
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [ ]:
a[:, :, np.newaxis].shape

(3, 4, 1)

In [ ]:
np.newaxis is None

True

np.newaxis 대신에 None을 써도 된다.  
None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.   
numpy를 만들 때 python의 모든 연산자를 다 사용해서 남는 연산자가 없었다.   
그래서 None을 이용했다.

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### expand_dims

In [ ]:
np.expand_dims(a, 0) #a[np.newaxis. :, :] 같다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a[np.newaxis, :, :] # a[np.newaxis] 같다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a, 1) #a[:, np.newaxis, :] 같다.

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [ ]:
np.expand_dims(a, 2) #a[:, :, np.newaxis] 같다.

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### array 한 줄로 펴기

####flatten

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#flatten()은 결과를 return하고 메모리의 값은 변경되지 않는다.
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###서로 차원 교환

####swapaxes

In [ ]:
a = np.array([[1], [2]]) #2차원 2행 1행
a

array([[1],
       [2]])

In [ ]:
a.shape

(2, 1)

In [ ]:
#a의 0번 차원과 1번 차원을 서로 바꾼다.
b = np.swapaxes(a, 1, 0)
b

array([[1, 2]])

In [ ]:
a.T

array([[1, 2]])